del *.*~ /s 
del *~ /s 
del *.a /s 
del *.aux /s 
del *.backup /s 
del *.bsc /s 
del *.blg /s 
del *.exe /s 
del *.idb /s 
del *.idx /s 
del *.ilg /s 
del *.ind /s 
del *.ilk /s 
del *.ipch /s 
del *.lib /s 
del *.log /s 
del *.lastbuildstate /s 
del *.manifest /s 
del *.o /s 
del *.obj /s 
del *.old /s 
del *.out /s 
del *.pdb /s 
del *.sbr /s 
del *.tlog /s 
del *.toc /s 
del *.tps /s 
del *.unsuccessfulbuild /s 
del *.user /s 


